Failure # 1 (occurred at 2023-02-09_23-20-29)
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::SAC.__init__()[39m (pid=3897, ip=127.0.1.1, repr=SAC)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 239, in _setup
    self.add_workers(
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 612, in add_workers
    raise result.get()
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=3936, ip=127.0.1.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff875fe9670>)
KeyError: 'darm/HalfCheetah-v1'

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.__init__()[39m (pid=3936, ip=127.0.1.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff875fe9670>)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/env/utils.py", line 50, in _gym_env_creator
    return gym.make(env_descriptor, **env_context)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 185, in spec
    raise error.DeprecatedEnv(
gym.error.DeprecatedEnv: Env darm/HalfCheetah-v1 not found (valid versions include ['HalfCheetah-v2', 'HalfCheetah-v3'])

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.__init__()[39m (pid=3936, ip=127.0.1.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff875fe9670>)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 585, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/env/utils.py", line 52, in _gym_env_creator
    raise EnvError(ERR_MSG_INVALID_ENV_DESCRIPTOR.format(env_descriptor))
ray.rllib.utils.error.EnvError: The env string you provided ('darm/HalfCheetah-v1') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`

During handling of the above exception, another exception occurred:

[36mray::SAC.__init__()[39m (pid=3897, ip=127.0.1.1, repr=SAC)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/algorithms/sac/sac.py", line 344, in __init__
    super().__init__(*args, **kwargs)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 441, in __init__
    super().__init__(
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 191, in __init__
    raise e.args[0].args[2]
ray.rllib.utils.error.EnvError: The env string you provided ('darm/HalfCheetah-v1') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`

